### ISSUE TITLE
Projet Menu-Server: déplacer la description de l'architecture plus tard

### ISSUE THREAD

**Issue by dduportal** [cicd-lectures/slides#127]
Les slides après le diagramme https://cicd-lectures.github.io/slides/2023/#/architecture_du_projet dpouraient être déplacées dans la partie "git à plusieurs", juste avant l'exercice d'implémentation du DeleteMenu.

En effet, pas mal de contenu est traité entre les 2 et ce n'est plus frais dans la tête des étudiants

**Comment by jlevesy** [comment]
Je pense faire un chapitre dédié et rajouter des rappels de POO basiques pour rendre les choses plus digestes. Genre une classe, un contructeur, une methode, injection de dépendence, spring boot.

Je parlerais de l'architecture a ce moment la.

T'en dis quoi @dduportal ?

**Comment by jlevesy** [comment]
Draft visible la https://github.com/cicd-lectures/slides/pull/131. C'est du jus de cerveau pour l'instant.
