### ISSUE TITLE
CI: introduire les concepts de GHA inputs/outputs AVANT de les utiliser

### ISSUE THREAD

**Issue by dduportal** [cicd-lectures/slides#128]
L'exercice https://cicd-lectures.github.io/slides/2023/#/exercice_optimiser_avec_les_fonctionnalit%C3%A9s_du_moteur_de_ci manque un préliminaire (texte + diagramme) expliquant les inputs/outputs pour aider les étudiants à mieux comprendre le changement de paradigme "full CLI" à "full GHA".

Note: sera également fort aidé par #114 !

**Comment by jlevesy** [comment]
Fixed it.
